# Generated by Django 4.1.7 on 2023-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='website.skill'),
        ),
        migrations.AlterField(
            model_name='role',
            name='skills',
            field=models.ManyToManyField(blank=True, to='website.skill'),
        ),
    ]
