# Generated by Django 4.1.7 on 2023-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
