version: "3.9"

services:
  # Main website service
  main-back:
    build: "./main-back/"
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    ports:
      - "8000:8000"
    networks:
      - front
      - main-back
    depends_on:
      - main-back-db

  main-back-db:
    image: postgres
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - main-back
    volumes:
      - main-back-data:/var/lib/postgresql/data

  api:
    build: "./api/"
    ports:
      - "5000:5000"
    networks:
      - api-back
      - front
    depends_on:
      - api-db

  api-db:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=api
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=api
    command: mongod
    volumes:
      - api-bd-data:/var/lib/mongo
    networks:
      - api-back
networks:
  front:
  main-back:
  api-back:

volumes:
  main-back-data:
  api-bd-data:
