version: "3.9"

services:
  # Main website service
  main-back:
    build: "./main-back/"
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    ports:
      - "8000:8000"
    networks:
      - front
      - main-back
    depends_on:
      - main-back-db

  main-back-db:
    image: postgres
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - main-back
    volumes:
      - main-back-data:/var/lib/postgresql/data

networks:
  front:
  main-back:

volumes:
  main-back-data: